### PR TITLE
Install JDKs instead of JREs

### PR DESCRIPTION
**Pull request by nickva**
Since we need it to compile nouveau and that requires javac

### CODE REVIEW

**Comment by nickva** [comment]
```
C:\Users\...\couchdb-glazier [main ≡ +0 ~2 -0 !]> &.\bin\install_dependencies.ps1
Downloading OpenJDK 8 ...
Installing OpenJDK 8 ...
VALUE: &archiver.Zip{CompressionLevel:-1, OverwriteExisting:false, MkdirAll:false, SelectiveCompression:true, ImplicitTopLevelFolder:true, ContinueOnError:true, zw:(*zip.Writer)(nil), zr:(*zip.Reader)(nil), ridx:0}
Downloading OpenJDK 11 ...
Installing OpenJDK 11 ...
VALUE: &archiver.Zip{CompressionLevel:-1, OverwriteExisting:false, MkdirAll:false, SelectiveCompression:true, ImplicitTopLevelFolder:true, ContinueOnError:true, zw:(*zip.Writer)(nil), zr:(*zip.Reader)(nil), ridx:0}
C:\Users\...\couchdb-glazier [main ≡ +2 ~2 -0 !]>
```

Then after starting a shell:
```
C:\Users\vatam\asf [main ≡]> javac -version
javac 11.0.24
C:\Users\vatam\asf [main ≡]> java -version
openjdk version "11.0.24" 2024-07-16 LTS
OpenJDK Runtime Environment Zulu11.74+15-CA (build 11.0.24+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.74+15-CA (build 11.0.24+8-LTS, mixed mode)
```

**Review by big-r81 — APPROVED** [review]

**Comment by big-r81** [comment]
I'm trying to remember why we needed the old JDK8?

**Comment by pgj** [comment]
https://github.com/apache/couchdb-glazier/pull/23

**Comment by big-r81** [comment]
Ah that thing called Clouseau needs JDK8 😉

**Pull request merged**
